spring:
  threads:
    virtual:
      enabled: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://49.50.167.118:3306/jpa_performance?zeroDateTimeBehavior=convertToNull&characterEncoding=utf8&serverTimezone=Asia/Seoul&useSSL=false
    username: ${dbId}
    password: ${dbPassword}
    hikari:
      maximum-pool-size: 20

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        show-sql: true
        default_batch_fetch_size: 100
    open-in-view: false
  ai:
    openai:
      api-key:  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa




logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: trace